version: '3'
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    mem_limit: 4G
    memswap_limit: 32G
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - type: bind
        source: ./notebooks
        target: /app
      - type: bind
        source: ./.jupyter
        target: /root/.jupyter