version: '3'
services:
  jupyterlab:
    image: acezhaoy/jupyterlab-cuda12.3.2:latest
    restart: always
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - type: bind
        source: ./notebooks
        target: /app
      - type: bind
        source: ./.jupyter
        target: /root/.jupyter