services:
  gate:
    image: acezhaoy/alpine-tz
    container_name: useful-gate
    restart: always
    working_dir: /app
    ports:
      - "80:80"
    volumes:
      - $PROJECT_BASE_PATH/gate/bin:/app
    command: ./gate
    networks:
      mywebnet:
        aliases:
          - svc-gate.default.svc.cluster.local
  user:
    image: acezhaoy/alpine-tz
    container_name: useful-user
    restart: always
    working_dir: /app
    ports:
      - "8081:80"
    volumes:
      - $PROJECT_BASE_PATH/user/bin:/app
    command: ./user
    networks:
      mywebnet:
        aliases:
          - svc-user.default.svc.cluster.local
  data:
    image: acezhaoy/alpine-tz
    container_name: useful-data
    restart: always
    working_dir: /app
    ports:
      - "8082:80"
    volumes:
      - $PROJECT_BASE_PATH/data/bin:/app
    command: ./data
    networks:
      mywebnet:
        aliases:
          - svc-data.default.svc.cluster.local
networks:
  mywebnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.101.1.0/24