version: '3'
services:
  nginx:
    image: nginx:1.16.0
    restart: always
    ports:
    - "${NGINX_HTTP_HOST_PORT}:80"
    - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
    - ${NGINX_CONF_DIR}:/opt/app/nginx/conf/conf.d
    - ${NGINX_SSL_DIR}:/opt/app/nginx/conf/ssl
    - ${SOURCE_DIR}:/opt/case
    - ${NGINX_LOG_DIR}:/opt/app/nginx/logs
    networks:
      - mywebnet
    links:
      - php
  php:
    image: php:7.4.8
    restart: always
    security_opt:
      - seccomp:unconfined
    #cap_add:
    #  - SYS_PTRACE
    ports:
      - "9100:9100"
    volumes:
    - ${SOURCE_DIR}:/opt/case
    - ${PHP_LOG_DIR}:/opt/logs/php
    networks:
      - mywebnet
  hyperf:
    image: hyperf/hyperf:7.4-alpine-v3.11-swoole
    restart: always
    ports:
      - "9501:9501"
    privileged: true
    tty: true
    command: "php /opt/case/assetshyperf/bin/hyperf.php start"
    volumes:
      - ${SOURCE_DIR}:/opt/case
    networks:
      - mywebnet
  mysql:
    image: mysql:5.7.33
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ${MYSQL_MY_CNF}:/etc/mysql/mysql.conf.d/my.cnf
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mywebnet
  redis:
    image: bitnami/redis:5.0.14
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ${REDIS_CONF}:/opt/bitnami/redis/etc/redis.conf
      - ${REDIS_DATA}:/bitnami/redis/data
    networks:
      - mywebnet
networks:
  mywebnet:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.10.0/24