version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 654321
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb_data:/data/db
